#!/bin/bash
set -e
DIR="${EXPORT_DIR:-export/web}"
MODE="--export-release"
[ "${DEBUG_BUILD}" = "true" ] && MODE="--export-debug"
mkdir -p "$DIR"
~/Завантажене/Godot_v4.6-stable_linux.x86_64 --headless $MODE "Web" "$DIR/deadly-pool.html"
echo "Done: $(du -sh "$DIR/" | cut -f1) -> $DIR/"
echo ""
echo "To test locally with required headers:"
echo "  cd $DIR && python3 -c \""
echo "import http.server, functools"
echo "Handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory='.')"
echo "class COOPHandler(Handler):"
echo "    def end_headers(self):"
echo "        self.send_header('Cross-Origin-Opener-Policy', 'same-origin')"
echo "        self.send_header('Cross-Origin-Embedder-Policy', 'require-corp')"
echo "        super().end_headers()"
echo "http.server.HTTPServer(('', 8000), COOPHandler).serve_forever()\""
echo ""
echo "Then open http://localhost:8000/deadly-pool.html"
